# Chapter 1

In [7]:
import numpy as np
x=np.array([1.0,2.,3.])
print(x)
type(x)

[ 1.  2.  3.]


numpy.ndarray

Broadcast: expansion of a scalar value to matrix composing with the value

In [10]:
A=np.array([[1,2],[3,4]])
B=np.array([10])
C=np.array([10,20])
print(A*B)
print(A*C)

[[10 20]
 [30 40]]
[[10 40]
 [30 80]]


1장 정리
* 파이썬 특징: 간단, 익히기 쉬움, 오픈 소스<br>
* 실행방식에 interpreter, script file 두 가지<br>
* 넘파이는 다차원 배열을 다루는 편리한 메소드를 많이 제공한다.<br>

---
# Chapter 2

perceptron (algorithm):<br>
    * Frank Rosenblatt, 1957
    * origin of neural network
    * output single signal from the multiple signals (input)

AND function w/o bias concept

In [11]:
def AND(x1,x2):
    w1,w2,theta=0.5,0.5,0.7
    tmp=x1*w1+x2*w2
    if tmp<=theta:
        return 0
    elif tmp>theta:
        return 1

In [12]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

0
0
0
1


AND function w bias concept

In [13]:
def AND(x1,x2):
    x=np.array([x1,x2])
    w=np.array([0.5,0.5])
    b=-0.7
    tmp=np.sum(w*x)+b
    if tmp<=0:return 0
    else: return 1

In [14]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

0
0
0
1


In [19]:
def NAND(x1,x2):
    x=np.array([x1,x2])
    w=np.array([-0.5,-0.5])
    b=0.7
    tmp=np.sum(w*x)+b
    if tmp<=0:return 0
    else: return 1
def OR(x1,x2):
    x=np.array([x1,x2])
    w=np.array([0.5,0.5])
    b=-0.2
    tmp=np.sum(w*x)+b
    if tmp<=0:return 0
    else: return 1

In [21]:
print(NAND(0,0))
print(NAND(1,0))
print(NAND(0,1))
print(NAND(1,1))

1
1
1
0


In [22]:
print(OR(0,0))
print(OR(1,0))
print(OR(0,1))
print(OR(1,1))

0
1
1
1


limitation of a perceptron
    * XOR gate 표현 불가
    * 직선 하나로 나눈 영역 (선형)만 표현할 수 있다
    * 곡선(비선형) 영역 표현 불가
    * 엄밀히 말해, 단층 퍼셉트론으로는 비선형 영역을 분리할 수 없다. 

multi-layer perceptron:<br>
    perceptron이 층을 이루게 되면 XOR 표현이 가능해진다

In [30]:
def XOR(x1,x2):
    s1=NAND(x1,x2)
    s2=OR(x1,x2)
    y=AND(s1,s2)
    return y

In [31]:
print(XOR(0,0))
print(XOR(1,0))
print(XOR(0,1))
print(XOR(1,1))

0
1
1
0


다층 퍼셉트론은 이론적으로 2층 이기만해도 컴퓨터를 만들 수 있다. 
<br>정확히는 활성 함수로 비선형인 시그모이드 함수를 이용하면 임의의 함수를 표현할 수 있다. 
<br>실제로는 가중치를 설정해야하는 문제로 컴퓨터를 만들 순 없다.
<br>실제 컴퓨터는 NAND 등 저수준 소자에서 시작하여 컴퓨터를 만드는데 필요한 부품(모듈)을 단계적으로 만들어간다. 
<br>즉, 처음엔 AND와 OR 게이트, 그다음 반가산기와 전가산기, 그다음 산술 논리 연산 장치, 그다음 CPU 식으로 만들어진다. 
<br>따라서 퍼셉트론으로 표현하는 컴퓨터도 2층이 아닌 여러 층을 다시 층층이 겹친 구조로 만들게 된다. 

2장 정리:
    * 퍼셉트론은 입출력을 갖춘 알고리즘
    * 퍼셉트론은 가중치와 편향을 매개변수로 설정
    * 퍼셉트론은 AND, OR 게이트 등의 논리 회로를 표현할 수 있다.
    * 단층 퍼셉트론은 XOR 게이트 표현 못함, 다층으론 가능
    * 단층 퍼셉트론은 선형 영역만 표현할 수 있고, 다층은 비선형 영역도 표현 가능
    * 다층 퍼셉트론은 이론상 컴퓨터를 표현 가능