In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.examples.tutorials.mnist import input_data

In [28]:
x=tf.Variable(2.)
y=tf.Variable(x.initialized_value()+3.)
print(x)
init=tf.global_variables_initializer()
sess= tf.Session()
sess.run(init)
print(sess.run(x))
print(sess.run(y))
sess.close()

<tf.Variable 'Variable_19:0' shape=() dtype=float32_ref>
2.0
5.0


In [32]:
w1=tf.Variable(tf.random_normal([784,100],stddev=0.35))
w2=tf.Variable(w1.initialized_value()+3.)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(w1))
print(sess.run(w2))
print(w2.get_shape())

[[-0.14025614  0.04376408  0.18988013 ... -0.17712922 -0.42585528
   0.44010812]
 [ 0.01574274  0.14469273 -0.26884836 ... -0.76281554 -0.21140543
  -0.39140853]
 [ 0.05313073 -0.2635982  -0.00468095 ... -0.66525173 -0.18226872
  -0.1152504 ]
 ...
 [ 0.37607616  0.14300135 -0.7089504  ... -0.02461854  0.41150895
  -0.46361056]
 [-0.17524214  0.62494314 -0.66740364 ... -0.3519176  -0.11494869
   0.35009918]
 [-0.47768554  0.1527609   0.16793871 ... -0.21367788  0.00151488
   0.2755428 ]]
[[2.8597438 3.043764  3.1898801 ... 2.8228707 2.5741448 3.440108 ]
 [3.0157428 3.1446927 2.7311516 ... 2.2371845 2.7885945 2.6085916]
 [3.0531306 2.7364018 2.9953191 ... 2.3347483 2.8177314 2.8847497]
 ...
 [3.3760762 3.1430013 2.2910495 ... 2.9753814 3.411509  2.5363894]
 [2.8247578 3.6249433 2.3325963 ... 2.6480825 2.8850513 3.350099 ]
 [2.5223145 3.152761  3.1679387 ... 2.786322  3.001515  3.2755427]]
(784, 100)


In [33]:
saver=tf.train.Saver()
# saver=tf.train.Saver(max_to_keep=4, keep_checkpoint_every_n_hours=2)
# 최근 2시간동안 4개의 모델만 저장한다.

save_path='./tmp/test.ckpt'
saver.save(sess,save_path)
# saver.save(sess, save_path, global_step=1000) 
# 1000 반복 마다 model 저장

# saver.save(sess, save_path, global_step=step,write_meta_graph=False) 
# 모델 값만 저장하고 graph 는 저장안함
tf.reset_default_graph()
load_path=save_path+'.meta'
saver=tf.train.import_meta_graph(load_path)
saver.restore(sess,tf.train.latest_checkpoint('./tmp'))
print(sess.run(w1))
print(sess.run(w2))
sess.close()

INFO:tensorflow:Restoring parameters from ./tmp\test.ckpt
[[-0.14025614  0.04376408  0.18988013 ... -0.17712922 -0.42585528
   0.44010812]
 [ 0.01574274  0.14469273 -0.26884836 ... -0.76281554 -0.21140543
  -0.39140853]
 [ 0.05313073 -0.2635982  -0.00468095 ... -0.66525173 -0.18226872
  -0.1152504 ]
 ...
 [ 0.37607616  0.14300135 -0.7089504  ... -0.02461854  0.41150895
  -0.46361056]
 [-0.17524214  0.62494314 -0.66740364 ... -0.3519176  -0.11494869
   0.35009918]
 [-0.47768554  0.1527609   0.16793871 ... -0.21367788  0.00151488
   0.2755428 ]]
[[2.8597438 3.043764  3.1898801 ... 2.8228707 2.5741448 3.440108 ]
 [3.0157428 3.1446927 2.7311516 ... 2.2371845 2.7885945 2.6085916]
 [3.0531306 2.7364018 2.9953191 ... 2.3347483 2.8177314 2.8847497]
 ...
 [3.3760762 3.1430013 2.2910495 ... 2.9753814 3.411509  2.5363894]
 [2.8247578 3.6249433 2.3325963 ... 2.6480825 2.8850513 3.350099 ]
 [2.5223145 3.152761  3.1679387 ... 2.786322  3.001515  3.2755427]]


In [43]:
tf.reset_default_graph()
w1=tf.placeholder(tf.float32, name='w1')
w2=tf.placeholder(tf.float32, name='w2')
b=tf.Variable(2.,dtype=tf.float32,name='bias')
feed_dict={'w1': 2., 'w2': 4.}

w3=w1+w2
w4=tf.multiply(w3,b, name='w4')
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
saver=tf.train.Saver()
result=sess.run(w4,feed_dict={w1:feed_dict['w1'],w2:feed_dict['w2']})
print(result)
saver.save(sess,'./tmp/test',global_step=1000)
sess.close()

12.0


In [46]:
tf.reset_default_graph()
sess=tf.Session()
saver=tf.train.import_meta_graph('./tmp/test-1000.meta')
saver.restore(sess,tf.train.latest_checkpoint('./tmp'))

graph=tf.get_default_graph()
w1 = graph.get_tensor_by_name("w1:0")
w2 = graph.get_tensor_by_name("w2:0")
feed_dict = {w1:13.0, w2:17.0}
w4 = graph.get_tensor_by_name("w4:0")
print (sess.run(w4,feed_dict))
sess.close()

INFO:tensorflow:Restoring parameters from ./tmp\test-1000
60.0
